from google.genai import types as genai_types

async def call_agent_async(runner, user_id: str, session_id: str, query: str):
    """Process a user query through the agent runner asynchronously."""

    user_message = genai_types.Content(
        role="user",
        parts=[genai_types.Part(text=query)],
    )

    print("\n--- Running agent asynchronously ---\n")

    events = runner.run_async(
        user_id=user_id,
        session_id=session_id,
        new_message=user_message,
    )

    final_response_text = None

    async for event in events:

        if event.is_final_response() and event.content is not None:
            text_parts = [
                part.text
                for part in event.content.parts
                if hasattr(part, "text") and part.text is not None
            ]
            final_response_text = "".join(text_parts)
    if final_response_text is None:
        final_response_text = "[No response generated by the agent.]"

    print(f"Agent: {final_response_text}\n")
    return final_response_text